Drafting/output
CCOMS-UAM/yos-award pull request #9
Opened 2022-12-15 13:52 UTC by Leafrancia

Draft of the output part of the project proposal for the YOS award

2022-12-16 08:42 UTC, robertomediavilla commented
First section ("Benefits") edited. The second sub-section ("Lessons learnt") is not focused. You can keep the introduction in that subsection but then you need to move to list actual lessons learnt, e.g., how hard it is to write a manuscript using GitHub (and why it is important), importance of sharing preprints on ResearchGate for instance, etc.

2022-12-16 09:20 UTC, robertomediavilla requested changes
First section ("Benefits") edited. The second sub-section ("Lessons learnt") is not focused. You can keep the introduction in that subsection but then you need to move to list actual lessons learnt, e.g., how hard it is to write a manuscript using GitHub (and why it is important), importance of sharing preprints on ResearchGate for instance, etc.

2022-12-16 09:29 UTC, DaniMori requested changes
Well done @Leafrancia ! I really have only two suggestions, the rest are comments we may want to discuss or consider further.

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
>  -   [*Benefits*]{.underline}*: What benefits were realised (to date) through
Please @Leafrancia , note there is only one text field (where it says `<!--# blank field -->`) so all the text should go there.

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +As a leading international research group and a World Health Organization's
I'm not sure if we can call ourselves "leading research group"...

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +the European Union (EU). This may potentially spread through different
This sounds great and is very well written. However, I have the concern that this is not true, at least up to now, Remember we are talking here about "what we have achieved so far".

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +minutes. By taking this approach, we have not only foster a stronger open
"not only _fostered_..."

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +research community.For example,in the EU-funded project RESPOND, we have already
"community. For example" (space after the point)

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +research community.For example,in the EU-funded project RESPOND, we have already
Has that article used Github actually? If you want an example that uses it, you can link this repo: https://github.com/CCOMS-UAM/mapping-initiatives

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +research community.For example,in the EU-funded project RESPOND, we have already
Also, mind these sentences dismissed from the "Description" section:

https://github.com/CCOMS-UAM/yos-award/blob/29e6f2eff0a4952bc8a02a103b6d237f2c23602b/output/Form.md?plain=1#L65

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +but also to how the study developed.
Great! This is exactly what I try to convey in "Description"

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +accessible to all. This increases the transparency of a study and facilitates
Excellent! Mind also these lines dismissed from "Description":

https://github.com/CCOMS-UAM/yos-award/blob/29e6f2eff0a4952bc8a02a103b6d237f2c23602b/output/Form.md?plain=1#L58

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +worked but also what led to an error. This written trace allowed us to save time
"what led _to error_"

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +information.
This is great! I would also add something about the use of Opal (you may need help/input from @robertomediavilla and/or @Cristrinaranjus for that).

Also, something about the challenges of using these technologies would be in place. That would help us justify the "Follow-up" section (investing in training courses)

2022-12-16 09:29 UTC, DaniMori commented on output/Form.md
> +<!--# blank field, 321 words -->
Leave only word count, i.e.:

 ```
<!--# 321 words -->
```

2022-12-19 09:34 UTC, DaniMori approved these changes

2022-12-21 09:47 UTC, Cristrinaranjus approved these changes

2022-12-21 10:15 UTC, robertomediavilla approved these changes

2022-12-21 10:16 UTC, robertomediavilla approved these changes

2022-12-21 10:24 UTC, JesusSierralaya approved these changes

2022-12-21 10:41 UTC, Cristrinaranjus approved these changes

2022-12-21 11:07 UTC, robertomediavilla commented
@DaniMori I think your approval is pending on this pull request. thanks!

2022-12-21 11:29 UTC, DaniMori commented on output/Form.md
> +approach, we aims not only to develop a stronger open science practice within
"we _aim_"

2022-12-21 11:30 UTC, DaniMori commented on output/Form.md
> +institutes in the region and improve reproducibility rates for the whole
"institutions"?

2022-12-21 11:30 UTC, DaniMori commented on output/Form.md
> +research community. For example,in the EU-funded project RESPOND, we have
space after comma

2022-12-21 11:32 UTC, DaniMori commented on output/Form.md
> +possible at all study sites. One of the main benefits of developing this
Empashize here that they are all "text-based", and thus susceptible to version control?

2022-12-21 11:32 UTC, DaniMori commented on output/Form.md
> +interesting tool for the researcher himself. Indeed, having this history allowed
"researchers themselves" (gender neutral)

2022-12-21 11:33 UTC, DaniMori commented on output/Form.md
> +mistake while understanding why. Also, when we want to remember the previous
"mistakes"

2022-12-21 11:33 UTC, DaniMori approved these changes
My suggestions are only very minor and can be implemented in the final review of the template.

2022-12-21 11:37 UTC, merged